[phases.setup]
nixPkgs = ["python313", "postgresql_16.dev", "poppler_utils", "gcc", "tesseract4"]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng", "libpango-1.0-0", "libpangocairo-1.0-0", "libcairo2", "libgdk-pixbuf-2.0-0", "libffi-dev", "shared-mime-info"]
